kind: Secret
apiVersion: v1
metadata:
  name: quay-secret
  namespace: devcloud1user4-dev
  uid: bedf1153-5609-4cce-88ed-30b1fd217db2
  resourceVersion: '6207332286'
  creationTimestamp: '2026-10-07T10:03:55Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2026-10-07T10:03:55Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:.dockerconfigjson': {}
        'f:type': {}
data:
  .dockerconfigjson: eyJhdXRocyI6eyJxdWF5LmlvIjp7ImF1dGgiOiJaR1YyWTJ4dmRXUXhkWE5sY2pRNllqUklVMGgzVVRGRE1USm9RemcwVm1aRGRIRTJkbHByUzJFM1dVOXpSR2d3VFZoVVEweHRXVzlrVDNCMVJVOXJSRk4xY0VReVZrbFBUbG96U1M5aWRWQk1OVkpzVlVaNU1tbFRlV1JpUjBweWJGZDNZWGM5UFE9PSIsInVzZXJuYW1lIjoiZGV2Y2xvdWQxdXNlcjQiLCJwYXNzd29yZCI6ImI0SFNId1ExQzEyaEM4NFZmQ3RxNnZaa0thN1lPc0RoME1YVENMbVlvZE9wdUVPa0RTdXBEMlZJT05aM0kvYnVQTDVSbFVGeTJpU3lkYkdKcmxXd2F3PT0iLCJlbWFpbCI6ImRldmNsb3VkMXVzZXI0QGF0b21pY21haWwuaW8ifX19
type: kubernetes.io/dockerconfigjson
#{"auths":{"quay.io":{"auth":"ZGV2Y2xvdWQxdXNlcjQ6YjRIU0h3UTFDMTJoQzg0VmZDdHE2dlprS2E3WU9zRGgwTVhUQ0xtWW9kT3B1RU9rRFN1cEQyVklPTlozSS9idVBMNVJsVUZ5MmlTeWRiR0pybFd3YXc9PQ==","username":"devcloud1user4","password":"b4HSHwQ1C12hC84VfCtq6vZkKa7YOsDh0MXTCLmYodOpuEOkDSupD2VIONZ3I/buPL5RlUFy2iSydbGJrlWwaw==","email":"devcloud1user4@atomicmail.io"}}}